/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// V1LabelSelectorRequirement A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
type V1LabelSelectorRequirement struct {
	Key *string `json:"key,omitempty"`
	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator *string `json:"operator,omitempty"`
	Values *[]string `json:"values,omitempty"`
}

// NewV1LabelSelectorRequirement instantiates a new V1LabelSelectorRequirement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1LabelSelectorRequirement() *V1LabelSelectorRequirement {
	this := V1LabelSelectorRequirement{}
	return &this
}

// NewV1LabelSelectorRequirementWithDefaults instantiates a new V1LabelSelectorRequirement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1LabelSelectorRequirementWithDefaults() *V1LabelSelectorRequirement {
	this := V1LabelSelectorRequirement{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *V1LabelSelectorRequirement) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LabelSelectorRequirement) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *V1LabelSelectorRequirement) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *V1LabelSelectorRequirement) SetKey(v string) {
	o.Key = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *V1LabelSelectorRequirement) GetOperator() string {
	if o == nil || o.Operator == nil {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LabelSelectorRequirement) GetOperatorOk() (*string, bool) {
	if o == nil || o.Operator == nil {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *V1LabelSelectorRequirement) HasOperator() bool {
	if o != nil && o.Operator != nil {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *V1LabelSelectorRequirement) SetOperator(v string) {
	o.Operator = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *V1LabelSelectorRequirement) GetValues() []string {
	if o == nil || o.Values == nil {
		var ret []string
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1LabelSelectorRequirement) GetValuesOk() (*[]string, bool) {
	if o == nil || o.Values == nil {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *V1LabelSelectorRequirement) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *V1LabelSelectorRequirement) SetValues(v []string) {
	o.Values = &v
}

func (o V1LabelSelectorRequirement) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Operator != nil {
		toSerialize["operator"] = o.Operator
	}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableV1LabelSelectorRequirement struct {
	value *V1LabelSelectorRequirement
	isSet bool
}

func (v NullableV1LabelSelectorRequirement) Get() *V1LabelSelectorRequirement {
	return v.value
}

func (v *NullableV1LabelSelectorRequirement) Set(val *V1LabelSelectorRequirement) {
	v.value = val
	v.isSet = true
}

func (v NullableV1LabelSelectorRequirement) IsSet() bool {
	return v.isSet
}

func (v *NullableV1LabelSelectorRequirement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1LabelSelectorRequirement(val *V1LabelSelectorRequirement) *NullableV1LabelSelectorRequirement {
	return &NullableV1LabelSelectorRequirement{value: val, isSet: true}
}

func (v NullableV1LabelSelectorRequirement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1LabelSelectorRequirement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


