/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// V1alpha1ApplicationSetSyncPolicy ApplicationSetSyncPolicy configures how generated Applications will relate to their ApplicationSet.
type V1alpha1ApplicationSetSyncPolicy struct {
	// PreserveResourcesOnDeletion will preserve resources on deletion. If PreserveResourcesOnDeletion is set to true, these Applications will not be deleted.
	PreserveResourcesOnDeletion *bool `json:"preserveResourcesOnDeletion,omitempty"`
}

// NewV1alpha1ApplicationSetSyncPolicy instantiates a new V1alpha1ApplicationSetSyncPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1ApplicationSetSyncPolicy() *V1alpha1ApplicationSetSyncPolicy {
	this := V1alpha1ApplicationSetSyncPolicy{}
	return &this
}

// NewV1alpha1ApplicationSetSyncPolicyWithDefaults instantiates a new V1alpha1ApplicationSetSyncPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1ApplicationSetSyncPolicyWithDefaults() *V1alpha1ApplicationSetSyncPolicy {
	this := V1alpha1ApplicationSetSyncPolicy{}
	return &this
}

// GetPreserveResourcesOnDeletion returns the PreserveResourcesOnDeletion field value if set, zero value otherwise.
func (o *V1alpha1ApplicationSetSyncPolicy) GetPreserveResourcesOnDeletion() bool {
	if o == nil || o.PreserveResourcesOnDeletion == nil {
		var ret bool
		return ret
	}
	return *o.PreserveResourcesOnDeletion
}

// GetPreserveResourcesOnDeletionOk returns a tuple with the PreserveResourcesOnDeletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ApplicationSetSyncPolicy) GetPreserveResourcesOnDeletionOk() (*bool, bool) {
	if o == nil || o.PreserveResourcesOnDeletion == nil {
		return nil, false
	}
	return o.PreserveResourcesOnDeletion, true
}

// HasPreserveResourcesOnDeletion returns a boolean if a field has been set.
func (o *V1alpha1ApplicationSetSyncPolicy) HasPreserveResourcesOnDeletion() bool {
	if o != nil && o.PreserveResourcesOnDeletion != nil {
		return true
	}

	return false
}

// SetPreserveResourcesOnDeletion gets a reference to the given bool and assigns it to the PreserveResourcesOnDeletion field.
func (o *V1alpha1ApplicationSetSyncPolicy) SetPreserveResourcesOnDeletion(v bool) {
	o.PreserveResourcesOnDeletion = &v
}

func (o V1alpha1ApplicationSetSyncPolicy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PreserveResourcesOnDeletion != nil {
		toSerialize["preserveResourcesOnDeletion"] = o.PreserveResourcesOnDeletion
	}
	return json.Marshal(toSerialize)
}

type NullableV1alpha1ApplicationSetSyncPolicy struct {
	value *V1alpha1ApplicationSetSyncPolicy
	isSet bool
}

func (v NullableV1alpha1ApplicationSetSyncPolicy) Get() *V1alpha1ApplicationSetSyncPolicy {
	return v.value
}

func (v *NullableV1alpha1ApplicationSetSyncPolicy) Set(val *V1alpha1ApplicationSetSyncPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1ApplicationSetSyncPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1ApplicationSetSyncPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1ApplicationSetSyncPolicy(val *V1alpha1ApplicationSetSyncPolicy) *NullableV1alpha1ApplicationSetSyncPolicy {
	return &NullableV1alpha1ApplicationSetSyncPolicy{value: val, isSet: true}
}

func (v NullableV1alpha1ApplicationSetSyncPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1ApplicationSetSyncPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
