/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// ApplicationApplicationSyncWindow struct for ApplicationApplicationSyncWindow
type ApplicationApplicationSyncWindow struct {
	Duration *string `json:"duration,omitempty"`
	Kind *string `json:"kind,omitempty"`
	ManualSync *bool `json:"manualSync,omitempty"`
	Schedule *string `json:"schedule,omitempty"`
}

// NewApplicationApplicationSyncWindow instantiates a new ApplicationApplicationSyncWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationApplicationSyncWindow() *ApplicationApplicationSyncWindow {
	this := ApplicationApplicationSyncWindow{}
	return &this
}

// NewApplicationApplicationSyncWindowWithDefaults instantiates a new ApplicationApplicationSyncWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationApplicationSyncWindowWithDefaults() *ApplicationApplicationSyncWindow {
	this := ApplicationApplicationSyncWindow{}
	return &this
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *ApplicationApplicationSyncWindow) GetDuration() string {
	if o == nil || o.Duration == nil {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationSyncWindow) GetDurationOk() (*string, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *ApplicationApplicationSyncWindow) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *ApplicationApplicationSyncWindow) SetDuration(v string) {
	o.Duration = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ApplicationApplicationSyncWindow) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationSyncWindow) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ApplicationApplicationSyncWindow) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ApplicationApplicationSyncWindow) SetKind(v string) {
	o.Kind = &v
}

// GetManualSync returns the ManualSync field value if set, zero value otherwise.
func (o *ApplicationApplicationSyncWindow) GetManualSync() bool {
	if o == nil || o.ManualSync == nil {
		var ret bool
		return ret
	}
	return *o.ManualSync
}

// GetManualSyncOk returns a tuple with the ManualSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationSyncWindow) GetManualSyncOk() (*bool, bool) {
	if o == nil || o.ManualSync == nil {
		return nil, false
	}
	return o.ManualSync, true
}

// HasManualSync returns a boolean if a field has been set.
func (o *ApplicationApplicationSyncWindow) HasManualSync() bool {
	if o != nil && o.ManualSync != nil {
		return true
	}

	return false
}

// SetManualSync gets a reference to the given bool and assigns it to the ManualSync field.
func (o *ApplicationApplicationSyncWindow) SetManualSync(v bool) {
	o.ManualSync = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *ApplicationApplicationSyncWindow) GetSchedule() string {
	if o == nil || o.Schedule == nil {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationApplicationSyncWindow) GetScheduleOk() (*string, bool) {
	if o == nil || o.Schedule == nil {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *ApplicationApplicationSyncWindow) HasSchedule() bool {
	if o != nil && o.Schedule != nil {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *ApplicationApplicationSyncWindow) SetSchedule(v string) {
	o.Schedule = &v
}

func (o ApplicationApplicationSyncWindow) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Duration != nil {
		toSerialize["duration"] = o.Duration
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.ManualSync != nil {
		toSerialize["manualSync"] = o.ManualSync
	}
	if o.Schedule != nil {
		toSerialize["schedule"] = o.Schedule
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationApplicationSyncWindow struct {
	value *ApplicationApplicationSyncWindow
	isSet bool
}

func (v NullableApplicationApplicationSyncWindow) Get() *ApplicationApplicationSyncWindow {
	return v.value
}

func (v *NullableApplicationApplicationSyncWindow) Set(val *ApplicationApplicationSyncWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationApplicationSyncWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationApplicationSyncWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationApplicationSyncWindow(val *ApplicationApplicationSyncWindow) *NullableApplicationApplicationSyncWindow {
	return &NullableApplicationApplicationSyncWindow{value: val, isSet: true}
}

func (v NullableApplicationApplicationSyncWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationApplicationSyncWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


