/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// ApplicationManagedResourcesResponse struct for ApplicationManagedResourcesResponse
type ApplicationManagedResourcesResponse struct {
	Items *[]V1alpha1ResourceDiff `json:"items,omitempty"`
}

// NewApplicationManagedResourcesResponse instantiates a new ApplicationManagedResourcesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationManagedResourcesResponse() *ApplicationManagedResourcesResponse {
	this := ApplicationManagedResourcesResponse{}
	return &this
}

// NewApplicationManagedResourcesResponseWithDefaults instantiates a new ApplicationManagedResourcesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationManagedResourcesResponseWithDefaults() *ApplicationManagedResourcesResponse {
	this := ApplicationManagedResourcesResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ApplicationManagedResourcesResponse) GetItems() []V1alpha1ResourceDiff {
	if o == nil || o.Items == nil {
		var ret []V1alpha1ResourceDiff
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationManagedResourcesResponse) GetItemsOk() (*[]V1alpha1ResourceDiff, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ApplicationManagedResourcesResponse) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []V1alpha1ResourceDiff and assigns it to the Items field.
func (o *ApplicationManagedResourcesResponse) SetItems(v []V1alpha1ResourceDiff) {
	o.Items = &v
}

func (o ApplicationManagedResourcesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationManagedResourcesResponse struct {
	value *ApplicationManagedResourcesResponse
	isSet bool
}

func (v NullableApplicationManagedResourcesResponse) Get() *ApplicationManagedResourcesResponse {
	return v.value
}

func (v *NullableApplicationManagedResourcesResponse) Set(val *ApplicationManagedResourcesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationManagedResourcesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationManagedResourcesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationManagedResourcesResponse(val *ApplicationManagedResourcesResponse) *NullableApplicationManagedResourcesResponse {
	return &NullableApplicationManagedResourcesResponse{value: val, isSet: true}
}

func (v NullableApplicationManagedResourcesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationManagedResourcesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
