/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// ApplicationResourceActionsListResponse struct for ApplicationResourceActionsListResponse
type ApplicationResourceActionsListResponse struct {
	Actions *[]V1alpha1ResourceAction `json:"actions,omitempty"`
}

// NewApplicationResourceActionsListResponse instantiates a new ApplicationResourceActionsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationResourceActionsListResponse() *ApplicationResourceActionsListResponse {
	this := ApplicationResourceActionsListResponse{}
	return &this
}

// NewApplicationResourceActionsListResponseWithDefaults instantiates a new ApplicationResourceActionsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationResourceActionsListResponseWithDefaults() *ApplicationResourceActionsListResponse {
	this := ApplicationResourceActionsListResponse{}
	return &this
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *ApplicationResourceActionsListResponse) GetActions() []V1alpha1ResourceAction {
	if o == nil || o.Actions == nil {
		var ret []V1alpha1ResourceAction
		return ret
	}
	return *o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationResourceActionsListResponse) GetActionsOk() (*[]V1alpha1ResourceAction, bool) {
	if o == nil || o.Actions == nil {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *ApplicationResourceActionsListResponse) HasActions() bool {
	if o != nil && o.Actions != nil {
		return true
	}

	return false
}

// SetActions gets a reference to the given []V1alpha1ResourceAction and assigns it to the Actions field.
func (o *ApplicationResourceActionsListResponse) SetActions(v []V1alpha1ResourceAction) {
	o.Actions = &v
}

func (o ApplicationResourceActionsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationResourceActionsListResponse struct {
	value *ApplicationResourceActionsListResponse
	isSet bool
}

func (v NullableApplicationResourceActionsListResponse) Get() *ApplicationResourceActionsListResponse {
	return v.value
}

func (v *NullableApplicationResourceActionsListResponse) Set(val *ApplicationResourceActionsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationResourceActionsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationResourceActionsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationResourceActionsListResponse(val *ApplicationResourceActionsListResponse) *NullableApplicationResourceActionsListResponse {
	return &NullableApplicationResourceActionsListResponse{value: val, isSet: true}
}

func (v NullableApplicationResourceActionsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationResourceActionsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


