/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// NotificationService struct for NotificationService
type NotificationService struct {
	Name *string `json:"name,omitempty"`
}

// NewNotificationService instantiates a new NotificationService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationService() *NotificationService {
	this := NotificationService{}
	return &this
}

// NewNotificationServiceWithDefaults instantiates a new NotificationService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationServiceWithDefaults() *NotificationService {
	this := NotificationService{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NotificationService) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationService) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NotificationService) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NotificationService) SetName(v string) {
	o.Name = &v
}

func (o NotificationService) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableNotificationService struct {
	value *NotificationService
	isSet bool
}

func (v NullableNotificationService) Get() *NotificationService {
	return v.value
}

func (v *NullableNotificationService) Set(val *NotificationService) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationService) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationService(val *NotificationService) *NullableNotificationService {
	return &NullableNotificationService{value: val, isSet: true}
}

func (v NullableNotificationService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
