/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// NotificationTemplate struct for NotificationTemplate
type NotificationTemplate struct {
	Name *string `json:"name,omitempty"`
}

// NewNotificationTemplate instantiates a new NotificationTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationTemplate() *NotificationTemplate {
	this := NotificationTemplate{}
	return &this
}

// NewNotificationTemplateWithDefaults instantiates a new NotificationTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationTemplateWithDefaults() *NotificationTemplate {
	this := NotificationTemplate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NotificationTemplate) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationTemplate) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NotificationTemplate) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NotificationTemplate) SetName(v string) {
	o.Name = &v
}

func (o NotificationTemplate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableNotificationTemplate struct {
	value *NotificationTemplate
	isSet bool
}

func (v NullableNotificationTemplate) Get() *NotificationTemplate {
	return v.value
}

func (v *NullableNotificationTemplate) Set(val *NotificationTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationTemplate(val *NotificationTemplate) *NullableNotificationTemplate {
	return &NullableNotificationTemplate{value: val, isSet: true}
}

func (v NullableNotificationTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
