/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// AccountCreateTokenResponse struct for AccountCreateTokenResponse
type AccountCreateTokenResponse struct {
	Token *string `json:"token,omitempty"`
}

// NewAccountCreateTokenResponse instantiates a new AccountCreateTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCreateTokenResponse() *AccountCreateTokenResponse {
	this := AccountCreateTokenResponse{}
	return &this
}

// NewAccountCreateTokenResponseWithDefaults instantiates a new AccountCreateTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCreateTokenResponseWithDefaults() *AccountCreateTokenResponse {
	this := AccountCreateTokenResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *AccountCreateTokenResponse) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCreateTokenResponse) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *AccountCreateTokenResponse) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *AccountCreateTokenResponse) SetToken(v string) {
	o.Token = &v
}

func (o AccountCreateTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableAccountCreateTokenResponse struct {
	value *AccountCreateTokenResponse
	isSet bool
}

func (v NullableAccountCreateTokenResponse) Get() *AccountCreateTokenResponse {
	return v.value
}

func (v *NullableAccountCreateTokenResponse) Set(val *AccountCreateTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCreateTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCreateTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCreateTokenResponse(val *AccountCreateTokenResponse) *NullableAccountCreateTokenResponse {
	return &NullableAccountCreateTokenResponse{value: val, isSet: true}
}

func (v NullableAccountCreateTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCreateTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


