/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// V1alpha1SCMProviderGenerator SCMProviderGenerator defines a generator that scrapes a SCMaaS API to find candidate repos.
type V1alpha1SCMProviderGenerator struct {
	AzureDevOps     *V1alpha1SCMProviderGeneratorAzureDevOps     `json:"azureDevOps,omitempty"`
	Bitbucket       *V1alpha1SCMProviderGeneratorBitbucket       `json:"bitbucket,omitempty"`
	BitbucketServer *V1alpha1SCMProviderGeneratorBitbucketServer `json:"bitbucketServer,omitempty"`
	// Which protocol to use for the SCM URL. Default is provider-specific but ssh if possible. Not all providers necessarily support all protocols.
	CloneProtocol *string `json:"cloneProtocol,omitempty"`
	// Filters for which repos should be considered.
	Filters *[]V1alpha1SCMProviderGeneratorFilter `json:"filters,omitempty"`
	Gitea   *V1alpha1SCMProviderGeneratorGitea    `json:"gitea,omitempty"`
	Github  *V1alpha1SCMProviderGeneratorGithub   `json:"github,omitempty"`
	Gitlab  *V1alpha1SCMProviderGeneratorGitlab   `json:"gitlab,omitempty"`
	// Standard parameters.
	RequeueAfterSeconds *string                         `json:"requeueAfterSeconds,omitempty"`
	Template            *V1alpha1ApplicationSetTemplate `json:"template,omitempty"`
}

// NewV1alpha1SCMProviderGenerator instantiates a new V1alpha1SCMProviderGenerator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1SCMProviderGenerator() *V1alpha1SCMProviderGenerator {
	this := V1alpha1SCMProviderGenerator{}
	return &this
}

// NewV1alpha1SCMProviderGeneratorWithDefaults instantiates a new V1alpha1SCMProviderGenerator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1SCMProviderGeneratorWithDefaults() *V1alpha1SCMProviderGenerator {
	this := V1alpha1SCMProviderGenerator{}
	return &this
}

// GetAzureDevOps returns the AzureDevOps field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetAzureDevOps() V1alpha1SCMProviderGeneratorAzureDevOps {
	if o == nil || o.AzureDevOps == nil {
		var ret V1alpha1SCMProviderGeneratorAzureDevOps
		return ret
	}
	return *o.AzureDevOps
}

// GetAzureDevOpsOk returns a tuple with the AzureDevOps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetAzureDevOpsOk() (*V1alpha1SCMProviderGeneratorAzureDevOps, bool) {
	if o == nil || o.AzureDevOps == nil {
		return nil, false
	}
	return o.AzureDevOps, true
}

// HasAzureDevOps returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasAzureDevOps() bool {
	if o != nil && o.AzureDevOps != nil {
		return true
	}

	return false
}

// SetAzureDevOps gets a reference to the given V1alpha1SCMProviderGeneratorAzureDevOps and assigns it to the AzureDevOps field.
func (o *V1alpha1SCMProviderGenerator) SetAzureDevOps(v V1alpha1SCMProviderGeneratorAzureDevOps) {
	o.AzureDevOps = &v
}

// GetBitbucket returns the Bitbucket field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetBitbucket() V1alpha1SCMProviderGeneratorBitbucket {
	if o == nil || o.Bitbucket == nil {
		var ret V1alpha1SCMProviderGeneratorBitbucket
		return ret
	}
	return *o.Bitbucket
}

// GetBitbucketOk returns a tuple with the Bitbucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetBitbucketOk() (*V1alpha1SCMProviderGeneratorBitbucket, bool) {
	if o == nil || o.Bitbucket == nil {
		return nil, false
	}
	return o.Bitbucket, true
}

// HasBitbucket returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasBitbucket() bool {
	if o != nil && o.Bitbucket != nil {
		return true
	}

	return false
}

// SetBitbucket gets a reference to the given V1alpha1SCMProviderGeneratorBitbucket and assigns it to the Bitbucket field.
func (o *V1alpha1SCMProviderGenerator) SetBitbucket(v V1alpha1SCMProviderGeneratorBitbucket) {
	o.Bitbucket = &v
}

// GetBitbucketServer returns the BitbucketServer field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetBitbucketServer() V1alpha1SCMProviderGeneratorBitbucketServer {
	if o == nil || o.BitbucketServer == nil {
		var ret V1alpha1SCMProviderGeneratorBitbucketServer
		return ret
	}
	return *o.BitbucketServer
}

// GetBitbucketServerOk returns a tuple with the BitbucketServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetBitbucketServerOk() (*V1alpha1SCMProviderGeneratorBitbucketServer, bool) {
	if o == nil || o.BitbucketServer == nil {
		return nil, false
	}
	return o.BitbucketServer, true
}

// HasBitbucketServer returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasBitbucketServer() bool {
	if o != nil && o.BitbucketServer != nil {
		return true
	}

	return false
}

// SetBitbucketServer gets a reference to the given V1alpha1SCMProviderGeneratorBitbucketServer and assigns it to the BitbucketServer field.
func (o *V1alpha1SCMProviderGenerator) SetBitbucketServer(v V1alpha1SCMProviderGeneratorBitbucketServer) {
	o.BitbucketServer = &v
}

// GetCloneProtocol returns the CloneProtocol field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetCloneProtocol() string {
	if o == nil || o.CloneProtocol == nil {
		var ret string
		return ret
	}
	return *o.CloneProtocol
}

// GetCloneProtocolOk returns a tuple with the CloneProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetCloneProtocolOk() (*string, bool) {
	if o == nil || o.CloneProtocol == nil {
		return nil, false
	}
	return o.CloneProtocol, true
}

// HasCloneProtocol returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasCloneProtocol() bool {
	if o != nil && o.CloneProtocol != nil {
		return true
	}

	return false
}

// SetCloneProtocol gets a reference to the given string and assigns it to the CloneProtocol field.
func (o *V1alpha1SCMProviderGenerator) SetCloneProtocol(v string) {
	o.CloneProtocol = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetFilters() []V1alpha1SCMProviderGeneratorFilter {
	if o == nil || o.Filters == nil {
		var ret []V1alpha1SCMProviderGeneratorFilter
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetFiltersOk() (*[]V1alpha1SCMProviderGeneratorFilter, bool) {
	if o == nil || o.Filters == nil {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasFilters() bool {
	if o != nil && o.Filters != nil {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []V1alpha1SCMProviderGeneratorFilter and assigns it to the Filters field.
func (o *V1alpha1SCMProviderGenerator) SetFilters(v []V1alpha1SCMProviderGeneratorFilter) {
	o.Filters = &v
}

// GetGitea returns the Gitea field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetGitea() V1alpha1SCMProviderGeneratorGitea {
	if o == nil || o.Gitea == nil {
		var ret V1alpha1SCMProviderGeneratorGitea
		return ret
	}
	return *o.Gitea
}

// GetGiteaOk returns a tuple with the Gitea field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetGiteaOk() (*V1alpha1SCMProviderGeneratorGitea, bool) {
	if o == nil || o.Gitea == nil {
		return nil, false
	}
	return o.Gitea, true
}

// HasGitea returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasGitea() bool {
	if o != nil && o.Gitea != nil {
		return true
	}

	return false
}

// SetGitea gets a reference to the given V1alpha1SCMProviderGeneratorGitea and assigns it to the Gitea field.
func (o *V1alpha1SCMProviderGenerator) SetGitea(v V1alpha1SCMProviderGeneratorGitea) {
	o.Gitea = &v
}

// GetGithub returns the Github field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetGithub() V1alpha1SCMProviderGeneratorGithub {
	if o == nil || o.Github == nil {
		var ret V1alpha1SCMProviderGeneratorGithub
		return ret
	}
	return *o.Github
}

// GetGithubOk returns a tuple with the Github field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetGithubOk() (*V1alpha1SCMProviderGeneratorGithub, bool) {
	if o == nil || o.Github == nil {
		return nil, false
	}
	return o.Github, true
}

// HasGithub returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasGithub() bool {
	if o != nil && o.Github != nil {
		return true
	}

	return false
}

// SetGithub gets a reference to the given V1alpha1SCMProviderGeneratorGithub and assigns it to the Github field.
func (o *V1alpha1SCMProviderGenerator) SetGithub(v V1alpha1SCMProviderGeneratorGithub) {
	o.Github = &v
}

// GetGitlab returns the Gitlab field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetGitlab() V1alpha1SCMProviderGeneratorGitlab {
	if o == nil || o.Gitlab == nil {
		var ret V1alpha1SCMProviderGeneratorGitlab
		return ret
	}
	return *o.Gitlab
}

// GetGitlabOk returns a tuple with the Gitlab field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetGitlabOk() (*V1alpha1SCMProviderGeneratorGitlab, bool) {
	if o == nil || o.Gitlab == nil {
		return nil, false
	}
	return o.Gitlab, true
}

// HasGitlab returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasGitlab() bool {
	if o != nil && o.Gitlab != nil {
		return true
	}

	return false
}

// SetGitlab gets a reference to the given V1alpha1SCMProviderGeneratorGitlab and assigns it to the Gitlab field.
func (o *V1alpha1SCMProviderGenerator) SetGitlab(v V1alpha1SCMProviderGeneratorGitlab) {
	o.Gitlab = &v
}

// GetRequeueAfterSeconds returns the RequeueAfterSeconds field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetRequeueAfterSeconds() string {
	if o == nil || o.RequeueAfterSeconds == nil {
		var ret string
		return ret
	}
	return *o.RequeueAfterSeconds
}

// GetRequeueAfterSecondsOk returns a tuple with the RequeueAfterSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetRequeueAfterSecondsOk() (*string, bool) {
	if o == nil || o.RequeueAfterSeconds == nil {
		return nil, false
	}
	return o.RequeueAfterSeconds, true
}

// HasRequeueAfterSeconds returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasRequeueAfterSeconds() bool {
	if o != nil && o.RequeueAfterSeconds != nil {
		return true
	}

	return false
}

// SetRequeueAfterSeconds gets a reference to the given string and assigns it to the RequeueAfterSeconds field.
func (o *V1alpha1SCMProviderGenerator) SetRequeueAfterSeconds(v string) {
	o.RequeueAfterSeconds = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *V1alpha1SCMProviderGenerator) GetTemplate() V1alpha1ApplicationSetTemplate {
	if o == nil || o.Template == nil {
		var ret V1alpha1ApplicationSetTemplate
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1SCMProviderGenerator) GetTemplateOk() (*V1alpha1ApplicationSetTemplate, bool) {
	if o == nil || o.Template == nil {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *V1alpha1SCMProviderGenerator) HasTemplate() bool {
	if o != nil && o.Template != nil {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given V1alpha1ApplicationSetTemplate and assigns it to the Template field.
func (o *V1alpha1SCMProviderGenerator) SetTemplate(v V1alpha1ApplicationSetTemplate) {
	o.Template = &v
}

func (o V1alpha1SCMProviderGenerator) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AzureDevOps != nil {
		toSerialize["azureDevOps"] = o.AzureDevOps
	}
	if o.Bitbucket != nil {
		toSerialize["bitbucket"] = o.Bitbucket
	}
	if o.BitbucketServer != nil {
		toSerialize["bitbucketServer"] = o.BitbucketServer
	}
	if o.CloneProtocol != nil {
		toSerialize["cloneProtocol"] = o.CloneProtocol
	}
	if o.Filters != nil {
		toSerialize["filters"] = o.Filters
	}
	if o.Gitea != nil {
		toSerialize["gitea"] = o.Gitea
	}
	if o.Github != nil {
		toSerialize["github"] = o.Github
	}
	if o.Gitlab != nil {
		toSerialize["gitlab"] = o.Gitlab
	}
	if o.RequeueAfterSeconds != nil {
		toSerialize["requeueAfterSeconds"] = o.RequeueAfterSeconds
	}
	if o.Template != nil {
		toSerialize["template"] = o.Template
	}
	return json.Marshal(toSerialize)
}

type NullableV1alpha1SCMProviderGenerator struct {
	value *V1alpha1SCMProviderGenerator
	isSet bool
}

func (v NullableV1alpha1SCMProviderGenerator) Get() *V1alpha1SCMProviderGenerator {
	return v.value
}

func (v *NullableV1alpha1SCMProviderGenerator) Set(val *V1alpha1SCMProviderGenerator) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1SCMProviderGenerator) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1SCMProviderGenerator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1SCMProviderGenerator(val *V1alpha1SCMProviderGenerator) *NullableV1alpha1SCMProviderGenerator {
	return &NullableV1alpha1SCMProviderGenerator{value: val, isSet: true}
}

func (v NullableV1alpha1SCMProviderGenerator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1SCMProviderGenerator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
