/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// ClusterConnector struct for ClusterConnector
type ClusterConnector struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewClusterConnector instantiates a new ClusterConnector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterConnector() *ClusterConnector {
	this := ClusterConnector{}
	return &this
}

// NewClusterConnectorWithDefaults instantiates a new ClusterConnector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterConnectorWithDefaults() *ClusterConnector {
	this := ClusterConnector{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClusterConnector) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConnector) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClusterConnector) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClusterConnector) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ClusterConnector) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterConnector) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ClusterConnector) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ClusterConnector) SetType(v string) {
	o.Type = &v
}

func (o ClusterConnector) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableClusterConnector struct {
	value *ClusterConnector
	isSet bool
}

func (v NullableClusterConnector) Get() *ClusterConnector {
	return v.value
}

func (v *NullableClusterConnector) Set(val *ClusterConnector) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterConnector) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterConnector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterConnector(val *ClusterConnector) *NullableClusterConnector {
	return &NullableClusterConnector{value: val, isSet: true}
}

func (v NullableClusterConnector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterConnector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


