/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// V1alpha1Application struct for V1alpha1Application
type V1alpha1Application struct {
	Metadata  *V1ObjectMeta              `json:"metadata,omitempty"`
	Operation *V1alpha1Operation         `json:"operation,omitempty"`
	Spec      *V1alpha1ApplicationSpec   `json:"spec,omitempty"`
	Status    *V1alpha1ApplicationStatus `json:"status,omitempty"`
}

// NewV1alpha1Application instantiates a new V1alpha1Application object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1Application() *V1alpha1Application {
	this := V1alpha1Application{}
	return &this
}

// NewV1alpha1ApplicationWithDefaults instantiates a new V1alpha1Application object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1ApplicationWithDefaults() *V1alpha1Application {
	this := V1alpha1Application{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *V1alpha1Application) GetMetadata() V1ObjectMeta {
	if o == nil || o.Metadata == nil {
		var ret V1ObjectMeta
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1Application) GetMetadataOk() (*V1ObjectMeta, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *V1alpha1Application) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given V1ObjectMeta and assigns it to the Metadata field.
func (o *V1alpha1Application) SetMetadata(v V1ObjectMeta) {
	o.Metadata = &v
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *V1alpha1Application) GetOperation() V1alpha1Operation {
	if o == nil || o.Operation == nil {
		var ret V1alpha1Operation
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1Application) GetOperationOk() (*V1alpha1Operation, bool) {
	if o == nil || o.Operation == nil {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *V1alpha1Application) HasOperation() bool {
	if o != nil && o.Operation != nil {
		return true
	}

	return false
}

// SetOperation gets a reference to the given V1alpha1Operation and assigns it to the Operation field.
func (o *V1alpha1Application) SetOperation(v V1alpha1Operation) {
	o.Operation = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *V1alpha1Application) GetSpec() V1alpha1ApplicationSpec {
	if o == nil || o.Spec == nil {
		var ret V1alpha1ApplicationSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1Application) GetSpecOk() (*V1alpha1ApplicationSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *V1alpha1Application) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given V1alpha1ApplicationSpec and assigns it to the Spec field.
func (o *V1alpha1Application) SetSpec(v V1alpha1ApplicationSpec) {
	o.Spec = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1alpha1Application) GetStatus() V1alpha1ApplicationStatus {
	if o == nil || o.Status == nil {
		var ret V1alpha1ApplicationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1Application) GetStatusOk() (*V1alpha1ApplicationStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1alpha1Application) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given V1alpha1ApplicationStatus and assigns it to the Status field.
func (o *V1alpha1Application) SetStatus(v V1alpha1ApplicationStatus) {
	o.Status = &v
}

func (o V1alpha1Application) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Operation != nil {
		toSerialize["operation"] = o.Operation
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableV1alpha1Application struct {
	value *V1alpha1Application
	isSet bool
}

func (v NullableV1alpha1Application) Get() *V1alpha1Application {
	return v.value
}

func (v *NullableV1alpha1Application) Set(val *V1alpha1Application) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1Application) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1Application) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1Application(val *V1alpha1Application) *NullableV1alpha1Application {
	return &NullableV1alpha1Application{value: val, isSet: true}
}

func (v NullableV1alpha1Application) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1Application) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
