ARG REGISTRY=docker.io/library

FROM ${REGISTRY}/alpine:latest
WORKDIR /

RUN echo -e '#!/bin/sh\necho "Running dummy batch mover."' > /mover && \
  chmod +x /mover && \
  echo -e '#!/bin/sh\necho "Running dummy stream mover."' > /stream && \
  chmod +x /stream && \
  echo -e '#!/bin/sh\necho "Running dummy finalizer."' > /finalizer && \
  chmod +x /finalizer

ENTRYPOINT ["/mover"]
