FROM alpine:latest
WORKDIR /

RUN echo -e '#!/bin/sh\necho "Running mover."' > /mover && \
  chmod +x /mover && \
  echo -e '#!/bin/sh\necho "Running finalizer."' > /finalizer && \
  chmod +x /finalizer

ENTRYPOINT ["/mover"]