ARCH ?= amd64

export ROOT_DIR ?= .
export TOOLS_DIR := $(ROOT_DIR)/hack/tools
export TOOLBIN := $(TOOLS_DIR)/bin
export ABSTOOLBIN := $(shell pwd)/$(TOOLS_DIR)/bin
export KUBEBUILDER_ASSETS=$(ABSTOOLBIN)
export PATH:=$(ABSTOOLBIN):${PATH}
export LOGGING_VERBOSITY = -1 
export PRETTY_LOGGING = true

ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

GOPATH=$(shell go env GOPATH)
