# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: app.fybrik.io/v1beta1
kind: FybrikModule
metadata:
  name: delete
  namespace: fybrik-system
spec:
  chart:
    name: ghcr.io/raviv-s/delete-module-chart:0.0.0
  type: service
  capabilities:
    - capability: delete
      api:
          connection:
            name: delete-module
            delete-module:
              hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
              port: 80
              scheme: grpc
      supportedInterfaces: 
      - source:
          protocol: s3

