// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_credential_request.proto

package connectors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DatasetCredentialsRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DatasetId            string   `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatasetCredentialsRequest) Reset()         { *m = DatasetCredentialsRequest{} }
func (m *DatasetCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*DatasetCredentialsRequest) ProtoMessage()    {}
func (*DatasetCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f872171735e5f8ed, []int{0}
}

func (m *DatasetCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetCredentialsRequest.Unmarshal(m, b)
}
func (m *DatasetCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *DatasetCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetCredentialsRequest.Merge(m, src)
}
func (m *DatasetCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_DatasetCredentialsRequest.Size(m)
}
func (m *DatasetCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetCredentialsRequest proto.InternalMessageInfo

func (m *DatasetCredentialsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DatasetCredentialsRequest) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func init() {
	proto.RegisterType((*DatasetCredentialsRequest)(nil), "connectors.DatasetCredentialsRequest")
}

func init() {
	proto.RegisterFile("data_credential_request.proto", fileDescriptor_f872171735e5f8ed)
}

var fileDescriptor_f872171735e5f8ed = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x49, 0x2c, 0x49,
	0x8c, 0x4f, 0x2e, 0x4a, 0x4d, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0x89, 0x2f, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xce, 0xcf, 0xcb, 0x4b,
	0x4d, 0x2e, 0xc9, 0x2f, 0x2a, 0x56, 0x0a, 0xe4, 0x92, 0x74, 0x49, 0x2c, 0x49, 0x2c, 0x4e, 0x2d,
	0x71, 0x86, 0x2b, 0x2f, 0x0e, 0x82, 0x28, 0x17, 0x12, 0xe5, 0x62, 0x4b, 0x2c, 0x28, 0x88, 0xcf,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x4d, 0x2c, 0x28, 0xf0, 0x4c, 0x11, 0x92,
	0xe5, 0xe2, 0x4a, 0x81, 0xe8, 0x01, 0x49, 0x31, 0x81, 0xa5, 0x38, 0xa1, 0x22, 0x9e, 0x29, 0x4e,
	0xbc, 0x5c, 0xdc, 0xc9, 0xf9, 0xb9, 0x7a, 0x29, 0x89, 0x25, 0xb9, 0xa9, 0xc5, 0x19, 0x49, 0x6c,
	0x60, 0x4b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x08, 0x2c, 0xab, 0x6b, 0x95, 0x00, 0x00,
	0x00,
}
