{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "egeria") }}
{{- if include "fybrik.isEnabled" (tuple .Values.egeriaConnector.enabled $autoFlag) }}
apiVersion: v1
kind: Service
metadata:
  name: "egeria-connector"
  labels:
    app.kubernetes.io/component: egeria-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.egeriaConnector.service.type }}
  ports:
    - port: {{ .Values.egeriaConnector.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: egeria-connector
    {{- include "fybrik.selectorLabels" . | nindent 4 }}
{{- end }}
