# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# permissions to do edit m4dapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-m4d-role
rules:
- apiGroups:
  - ""  
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - m4dapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - m4dapplications/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-m4d-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-m4d-role
subjects:
- kind: ServiceAccount
  name: default
---
kind: Service
apiVersion: v1
metadata:
  name: datauserclient
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: gui    
---
kind: Service
apiVersion: v1
metadata:
  name: datauserserver
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gui    

