//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package catalog

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetAssetRequest) DeepCopyInto(out *GetAssetRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAssetRequest.
func (in *GetAssetRequest) DeepCopy() *GetAssetRequest {
	if in == nil {
		return nil
	}
	out := new(GetAssetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetAssetResponse) DeepCopyInto(out *GetAssetResponse) {
	*out = *in
	in.ResourceMetadata.DeepCopyInto(&out.ResourceMetadata)
	in.Details.DeepCopyInto(&out.Details)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAssetResponse.
func (in *GetAssetResponse) DeepCopy() *GetAssetResponse {
	if in == nil {
		return nil
	}
	out := new(GetAssetResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceColumn) DeepCopyInto(out *ResourceColumn) {
	*out = *in
	in.Tags.DeepCopyInto(&out.Tags)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceColumn.
func (in *ResourceColumn) DeepCopy() *ResourceColumn {
	if in == nil {
		return nil
	}
	out := new(ResourceColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceDetails) DeepCopyInto(out *ResourceDetails) {
	*out = *in
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceDetails.
func (in *ResourceDetails) DeepCopy() *ResourceDetails {
	if in == nil {
		return nil
	}
	out := new(ResourceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMetadata) DeepCopyInto(out *ResourceMetadata) {
	*out = *in
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.Geography != nil {
		in, out := &in.Geography, &out.Geography
		*out = new(string)
		**out = **in
	}
	in.Tags.DeepCopyInto(&out.Tags)
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = new([]ResourceColumn)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ResourceColumn, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMetadata.
func (in *ResourceMetadata) DeepCopy() *ResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(ResourceMetadata)
	in.DeepCopyInto(out)
	return out
}
