//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2022 IBM Corp.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package adminrules

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeOptimization) DeepCopyInto(out *AttributeOptimization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeOptimization.
func (in *AttributeOptimization) DeepCopy() *AttributeOptimization {
	if in == nil {
		return nil
	}
	out := new(AttributeOptimization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decision) DeepCopyInto(out *Decision) {
	*out = *in
	in.DeploymentRestrictions.DeepCopyInto(&out.DeploymentRestrictions)
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decision.
func (in *Decision) DeepCopy() *Decision {
	if in == nil {
		return nil
	}
	out := new(Decision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionPerCapability) DeepCopyInto(out *DecisionPerCapability) {
	*out = *in
	in.Decision.DeepCopyInto(&out.Decision)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionPerCapability.
func (in *DecisionPerCapability) DeepCopy() *DecisionPerCapability {
	if in == nil {
		return nil
	}
	out := new(DecisionPerCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionPolicy) DeepCopyInto(out *DecisionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionPolicy.
func (in *DecisionPolicy) DeepCopy() *DecisionPolicy {
	if in == nil {
		return nil
	}
	out := new(DecisionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationOutputStructure) DeepCopyInto(out *EvaluationOutputStructure) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(RuleDecisionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Optimize != nil {
		in, out := &in.Optimize, &out.Optimize
		*out = make([]OptimizationStrategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationOutputStructure.
func (in *EvaluationOutputStructure) DeepCopy() *EvaluationOutputStructure {
	if in == nil {
		return nil
	}
	out := new(EvaluationOutputStructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationStrategy) DeepCopyInto(out *OptimizationStrategy) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = make([]AttributeOptimization, len(*in))
		copy(*out, *in)
	}
	out.Policy = in.Policy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationStrategy.
func (in *OptimizationStrategy) DeepCopy() *OptimizationStrategy {
	if in == nil {
		return nil
	}
	out := new(OptimizationStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeType) DeepCopyInto(out *RangeType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeType.
func (in *RangeType) DeepCopy() *RangeType {
	if in == nil {
		return nil
	}
	out := new(RangeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Restriction) DeepCopyInto(out *Restriction) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(StringList, len(*in))
		copy(*out, *in)
	}
	if in.Range != nil {
		in, out := &in.Range, &out.Range
		*out = new(RangeType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Restriction.
func (in *Restriction) DeepCopy() *Restriction {
	if in == nil {
		return nil
	}
	out := new(Restriction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Restrictions) DeepCopyInto(out *Restrictions) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]Restriction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]Restriction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StorageAccounts != nil {
		in, out := &in.StorageAccounts, &out.StorageAccounts
		*out = make([]Restriction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Restrictions.
func (in *Restrictions) DeepCopy() *Restrictions {
	if in == nil {
		return nil
	}
	out := new(Restrictions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RuleDecisionList) DeepCopyInto(out *RuleDecisionList) {
	{
		in := &in
		*out = make(RuleDecisionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDecisionList.
func (in RuleDecisionList) DeepCopy() RuleDecisionList {
	if in == nil {
		return nil
	}
	out := new(RuleDecisionList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StringList) DeepCopyInto(out *StringList) {
	{
		in := &in
		*out = make(StringList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringList.
func (in StringList) DeepCopy() StringList {
	if in == nil {
		return nil
	}
	out := new(StringList)
	in.DeepCopyInto(out)
	return *out
}
