ROOT_DIR := ../../..
include $(ROOT_DIR)/Makefile.env
include $(ROOT_DIR)/hack/make-rules/tools.mk
DOCKER_NAME ?= datauserclient
DOCKER_TAGNAME ?= latest
DOCKER_FILE = Dockerfile
DOCKER_CONTEXT = .
GO_OUTPUT_FILE = datauserclient
include $(ROOT_DIR)/hack/make-rules/docker.mk




