.PHONY: all
all: helm-all

ROOT_DIR := ../..
DOCKER_NAME := m4d-template
DOCKER_TAGNAME := 0.1.0

include $(ROOT_DIR)/Makefile.env
include $(ROOT_DIR)/.mk/docker.mk
include $(ROOT_DIR)/.mk/helm.mk
include $(ROOT_DIR)/.mk/tools.mk
